In [81]:
# Link to team assignments: https://docs.google.com/spreadsheets/d/1kY9il3pFVcxS4xenocB2rk0-sXqm4YrhbHp4kBpZLac/edit?usp=sharing
# Download your section sheet as a CSV file and rename it as students.csv

import pandas as pd
import numpy as np
import random

In [82]:
# Fields available in students.csv
# team_id, team_name, student_email, student_name, assigned_IA, assigned_TA

# Read the CSV file into a Pandas dataframe
df = pd.read_csv("./students.csv")
# Check whether the email column is unique
df['student_email'].is_unique

True

In [83]:
# For security reasons, hide student email and last name
show_df = df[["team_id", "team_name", "student_name", "assigned_IA", "assigned_TA"]].copy()
show_df["student_name"] = df.apply(lambda x: x["student_name"].split(",")[1], axis=1)
# Lists out the dataframe
show_df

    team_id  team_name student_name assigned_IA assigned_TA
0        47        NaN       Linjun      Jiesen     Vineeth
1        47        NaN         Cate      Jiesen     Vineeth
2        47        NaN         Milo      Jiesen     Vineeth
3        47        NaN     Priyanka      Jiesen     Vineeth
4        48        NaN      Nainika      Jiesen     Vineeth
..      ...        ...          ...         ...         ...
59       61        NaN     Scarlett      Wenhua     Vineeth
60       62        NaN       Justin      Wenhua     Vineeth
61       62        NaN      Biancca      Wenhua     Vineeth
62       62        NaN        Baiyu      Wenhua     Vineeth
63       62        NaN         Ryan      Wenhua     Vineeth

[64 rows x 5 columns]

In [84]:
# Provides information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   team_id        64 non-null     int64
 1   team_name      0 non-null      float64
 2   student_email  64 non-null     object
 3   student_name   64 non-null     object
 4   assigned_IA    64 non-null     object
 5   assigned_TA    64 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 3.1+ KB

In [85]:
random_seed = 28
random.seed(random_seed)

In [86]:
# team_names = ["Algorithm Avengers",
#               "Dataset Dominators",
#               "Query Quirkies",
#               "Outlier Outlaws",
#               "Variable Variables",
#               "Team Beta",
#               "Array of Sunshine",
#               "CSV Crew",
#               "P-Value Posse",
#               "Regex Rebels",
#               "Database Maintenance Unit",
#               "Documentation Task Force",
#               "RIMAC Random Forests",
#               "Lost in Classification",
#               "Triton t-Tests"]

team_names = ["Inferential Insiders",
              "Model Mystics",
              "Statistical Sorcerers",
              "Regression Rangers",
              "Correlation Cavaliers",
              "Visualization Virtuosos",
              "Standard Deviation Squad",
              "Gilman Parking",
              "Logistically Regressed",
              "Geisel Gaussians",
              "Scripps Pier Pressure",
              "COGS 9 Team",
              "Project Procrastinators",
              "Assignment Due",
              "Wrangle Me This",
              "CENTR 222"]

# team_names = ["Hypothesis Hotshots",
#               "Entropy Enthusiasts",
#               "Python Pioneers",
#               "We Tried Linear Regression",
#               "Neural Network Nerds",
#               "Where's My Semicolon?",
#               "Bias Busters",
#               "Mean, Median, and Modeketeers",
#               "Data Entry Division",
#               "Group 2",
#               "Eucalyptus Ensemble",
#               "Price Center Predictors",
#               "Spreadsheet SIMPS",
#               "Go Greenies",
#               "Bland Brigade"]

random.shuffle(team_names)

In [88]:
# Assign team names
df["team_name"] = df["team_id"].apply(lambda team_id: team_names[team_id % len(team_names)])

In [89]:
# For security reasons, hide student email and last name
show_df = df[["team_id", "team_name", "student_name", "assigned_IA", "assigned_TA"]].copy()
show_df["student_name"] = df.apply(lambda x: x["student_name"].split(",")[1], axis=1)
# Lists out the dataframe
show_df

    team_id                team_name student_name assigned_IA assigned_TA
0        47       Regression Rangers       Linjun      Jiesen     Vineeth
1        47       Regression Rangers         Cate      Jiesen     Vineeth
2        47       Regression Rangers         Milo      Jiesen     Vineeth
3        47       Regression Rangers     Priyanka      Jiesen     Vineeth
4        48  Project Procrastinators      Nainika      Jiesen     Vineeth
..      ...                      ...          ...         ...         ...
59       61    Statistical Sorcerers     Scarlett      Wenhua     Vineeth
60       62              COGS 9 Team       Justin      Wenhua     Vineeth
61       62              COGS 9 Team      Biancca      Wenhua     Vineeth
62       62              COGS 9 Team        Baiyu      Wenhua     Vineeth
63       62              COGS 9 Team         Ryan      Wenhua     Vineeth

[64 rows x 5 columns]

In [90]:
# Write out to CSV file
df.to_csv("students.csv", index=False)