In [ ]:
# Link to team assignments: https://docs.google.com/spreadsheets/d/1kY9il3pFVcxS4xenocB2rk0-sXqm4YrhbHp4kBpZLac/edit?usp=sharing
# Download your section sheet as a CSV file and rename it as students.csv

import pandas as pd
import numpy as np
import random

In [ ]:
# Fields available in students.csv
# team_id, team_name, student_email, student_name, assigned_IA, assigned_TA

# Read the CSV file into a Pandas dataframe
df = pd.read_csv("./students.csv")
# Check whether the email column is unique
df['student_email'].is_unique

True

In [ ]:
# For security reasons, hide student email and last name
show_df = df[["team_id", "team_name", "student_name", "assigned_IA", "assigned_TA"]].copy()
show_df["student_name"] = df.apply(lambda x: x["student_name"].split(",")[1], axis=1)
# Lists out the dataframe
show_df

    team_id  team_name student_name assigned_IA assigned_TA
0        63        NaN       Aranza    Harshita     Vineeth
1        63        NaN        Mehul    Harshita     Vineeth
2        63        NaN        Brian    Harshita     Vineeth
3        63        NaN        Aahil    Harshita     Vineeth
4        63        NaN       Kareen    Harshita     Vineeth
..      ...        ...          ...         ...         ...
57       76        NaN       Jojiro       Vicky     Vineeth
58       77        NaN        Alexa       Vicky     Vineeth
59       77        NaN       Camila       Vicky     Vineeth
60       77        NaN       Cooper       Vicky     Vineeth
61       77        NaN        Elvin       Vicky     Vineeth

[62 rows x 5 columns]

In [ ]:
# Provides information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   team_id        62 non-null     int64
 1   team_name      0 non-null      float64
 2   student_email  62 non-null     object
 3   student_name   62 non-null     object
 4   assigned_IA    62 non-null     object
 5   assigned_TA    62 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 3.0+ KB

In [ ]:
random_seed = 4
random.seed(random_seed)

In [ ]:
# team_names = ["Algorithm Avengers",
#               "Dataset Dominators",
#               "Query Quirkies",
#               "Outlier Outlaws",
#               "Variable Variables",
#               "Team Beta",
#               "Array of Sunshine",
#               "CSV Crew",
#               "P-Value Posse",
#               "Regex Rebels",
#               "Database Maintenance Unit",
#               "Documentation Task Force",
#               "RIMAC Random Forests",
#               "Lost in Classification",
#               "Triton t-Tests"]

# team_names = ["Inferential Insiders",
#               "Model Mystics",
#               "Statistical Sorcerers",
#               "Regression Rangers",
#               "Correlation Cavaliers",
#               "Visualization Virtuosos",
#               "Standard Deviation Squad",
#               "Gilman Parking",
#               "Logistically Regressed",
#               "Geisel Gaussians",
#               "Scripps Pier Pressure",
#               "COGS 9 Team",
#               "Project Procrastinators",
#               "Assignment Due",
#               "Wrangle Me This",
#               "CENTR 222"]

team_names = ["Hypothesis Hotshots",
              "Entropy Enthusiasts",
              "Python Pioneers",
              "We Tried Linear Regression",
              "Neural Network Nerds",
              "Where's My Semicolon?",
              "Bias Busters",
              "Mean, Median, and Modeketeers",
              "Data Entry Division",
              "Disneynand Datasets",
              "Eucalyptus Ensemble",
              "Price Center Predictors",
              "Spreadsheet SIMPS",
              "Go Greenies",
              "Bland Brigade"]

random.shuffle(team_names)

In [ ]:
# Assign team names
df["team_name"] = df["team_id"].apply(lambda team_id: team_names[team_id % len(team_names)])

In [ ]:
# For security reasons, hide student email and last name
show_df = df[["team_id", "team_name", "student_name", "assigned_IA", "assigned_TA"]].copy()
show_df["student_name"] = df.apply(lambda x: x["student_name"].split(",")[1], axis=1)
# Lists out the dataframe
show_df

    team_id              team_name student_name assigned_IA assigned_TA
0        63    Data Entry Division       Aranza    Harshita     Vineeth
1        63    Data Entry Division        Mehul    Harshita     Vineeth
2        63    Data Entry Division        Brian    Harshita     Vineeth
3        63    Data Entry Division        Aahil    Harshita     Vineeth
4        63    Data Entry Division       Kareen    Harshita     Vineeth
..      ...                    ...          ...         ...         ...
57       76            Go Greenies       Jojiro       Vicky     Vineeth
58       77  Where's My Semicolon?        Alexa       Vicky     Vineeth
59       77  Where's My Semicolon?       Camila       Vicky     Vineeth
60       77  Where's My Semicolon?       Cooper       Vicky     Vineeth
61       77  Where's My Semicolon?        Elvin       Vicky     Vineeth

[62 rows x 5 columns]

In [ ]:
# Write out to CSV file
df.to_csv("students.csv", index=False)